language: php

os: linux

dist: bionic

sudo: false

jobs:
    include:
        -
            php: 7.3
            services:
                - mysql
        -
            php: 7.4
            services:
                - mysql

cache:
    yarn: true
    directories:
        - ~/.composer/cache/files
        - $SYLIUS_CACHE_DIR

env:
    global:
        - APP_ENV=test
        - SYLIUS_CACHE_DIR=$HOME/.sylius-cache
        - SYLIUS_BUILD_DIR=etc/build

before_install:
    - phpenv config-rm xdebug.ini
    - echo "memory_limit=4096M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - mkdir -p "${SYLIUS_CACHE_DIR}"

install:
    - composer install --no-interaction --prefer-dist
    - (cd tests/Application && yarn install)

before_script:
    - (cd tests/Application && bin/console doctrine:database:create -vvv)
    - (cd tests/Application && bin/console doctrine:schema:create -vvv)
    - (cd tests/Application && bin/console assets:install public -vvv)
    - (cd tests/Application && bin/console cache:warmup -vvv)
    - (cd tests/Application && yarn build)

    # Configure display
    - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1680x1050x16
    - export DISPLAY=:99

    # Download Symfony command
    - wget https://get.symfony.com/cli/installer -O - | bash
    - mv ~/.symfony/bin/symfony $SYLIUS_CACHE_DIR

    # Download and configure ChromeDriver
    - |
        if [ ! -f $SYLIUS_CACHE_DIR/chromedriver ] || [ "$($SYLIUS_CACHE_DIR/chromedriver --version | grep -c 2.34)" = "0" ]; then
            curl http://chromedriver.storage.googleapis.com/2.34/chromedriver_linux64.zip > chromedriver.zip
            unzip chromedriver.zip
            chmod +x chromedriver
            mv chromedriver $SYLIUS_CACHE_DIR
        fi

    # Install certificates
    - $SYLIUS_CACHE_DIR/symfony server:ca:install

    # Run headless Chrome
    - google-chrome-stable --enable-automation --disable-background-networking --no-default-browser-check --no-first-run --disable-popup-blocking --disable-default-apps --allow-insecure-localhost --disable-translate --disable-extensions --no-sandbox --enable-features=Metal --headless --remote-debugging-port=9222 --window-size=2880,1800 --proxy-server='direct://' --proxy-bypass-list='*' http://127.0.0.1 > /dev/null 2>&1 &

    # Run webserver
    - $SYLIUS_CACHE_DIR/symfony server:start --port=8080 --dir=public --daemon

    # Run webserver
    - (cd tests/Application && $SYLIUS_CACHE_DIR/symfony server:start --port=8080 --dir=public --allow-http --no-tls --force-php-discovery --daemon)

script:
    - composer validate --strict
    - composer analyse

    - vendor/bin/behat -vvv --no-interaction --strict || vendor/bin/behat -vvv --no-interaction --strict --rerun
    - vendor/bin/phpspec run
    - vendor/bin/phpunit

after_failure:
    - vendor/lakion/mink-debug-extension/travis/tools/upload-textfiles "${SYLIUS_BUILD_DIR}/*.log"
